media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date, language ]
    fields:
      - { name: language, label: Language, type: select, options: [ { value: "en", label: "English" }, { value: "ar", label: "العربية" }, { value: "fr", label: "Français" }, { value: "es", label: "Español" } ], required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }
  
  - name: team
    label: Team Members
    type: collection
    path: _team
    view:
      fields: [ name, role, picture, language ]
    fields:
      - { name: language, label: Language, type: select, options: [ { value: "en", label: "English" }, { value: "ar", label: "العربية" }, { value: "fr", label: "Français" }, { value: "es", label: "Español" } ], required: true }
      - { name: name, label: Name, type: string, required: true }
      - { name: role, label: Role/Position, type: string, required: true }
      - { name: bio, label: Bio, type: text }
      - { name: picture, label: Profile Picture, type: image }
      - { name: email, label: Email, type: string }
      - { name: linkedin, label: LinkedIn URL, type: string }
      - { name: twitter, label: Twitter URL, type: string }
      - { name: github, label: GitHub URL, type: string }
      - { name: website, label: Personal Website, type: string }
  
  - name: events
    label: Events
    type: collection
    path: _events
    view:
      fields: [ title, date, type, isUpcoming, language ]
    fields:
      - { name: language, label: Language, type: select, options: [ { value: "en", label: "English" }, { value: "ar", label: "العربية" }, { value: "fr", label: "Français" }, { value: "es", label: "Español" } ], required: true }
      - { name: title, label: Event Title, type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: date, label: Start Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - { name: endDate, label: End Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - { name: location, label: Location, type: string }
      - { name: type, label: Event Type, type: select, options: [ { value: "conference", label: "Conference" }, { value: "workshop", label: "Workshop" }, { value: "meetup", label: "Meetup" }, { value: "webinar", label: "Webinar" }, { value: "other", label: "Other" } ] }
      - { name: coverImage, label: Cover Image, type: image }
      - { name: registrationUrl, label: Registration URL, type: string }
      - { name: isUpcoming, label: Is Upcoming Event, type: boolean, default: true }
      - { name: attendees, label: Expected Attendees, type: number }
      - { name: tags, label: Tags, type: text }